curl -X PUT -d '[{"key":{"encoding":"binary","data":"001011010"},"value":{"encoding":"string","data":"001010110"}},
   {
      "key":{
         "encoding":"string",
         "data":"key1"
      },
      "value":{
         "encoding":"string",
         "data":"value1"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key2"
      },
      "value":{
         "encoding":"string",
         "data":"value2"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key3"
      },
      "value":{
         "encoding":"string",
         "data":"value3"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key4"
      },
      "value":{
         "encoding":"string",
         "data":"value4"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key5"
      },
      "value":{
         "encoding":"string",
         "data":"value5"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key6"
      },
      "value":{
         "encoding":"string",
         "data":"value6"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key7"
      },
      "value":{
         "encoding":"string",
         "data":"value7"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key8"
      },
      "value":{
         "encoding":"string",
         "data":"value8"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key9"
      },
      "value":{
         "encoding":"string",
         "data":"value9"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key10"
      },
      "value":{
         "encoding":"string",
         "data":"value10"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key11"
      },
      "value":{
         "encoding":"string",
         "data":"value11"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key12"
      },
      "value":{
         "encoding":"string",
         "data":"value12"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key13"
      },
      "value":{
         "encoding":"string",
         "data":"value13"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key14"
      },
      "value":{
         "encoding":"string",
         "data":"value14"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key15"
      },
      "value":{
         "encoding":"string",
         "data":"value15"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key16"
      },
      "value":{
         "encoding":"string",
         "data":"value16"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key17"
      },
      "value":{
         "encoding":"string",
         "data":"value17"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key18"
      },
      "value":{
         "encoding":"string",
         "data":"value18"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key19"
      },
      "value":{
         "encoding":"string",
         "data":"value19"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key20"
      },
      "value":{
         "encoding":"string",
         "data":"value20"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key21"
      },
      "value":{
         "encoding":"string",
         "data":"value21"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key22"
      },
      "value":{
         "encoding":"string",
         "data":"value22"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key23"
      },
      "value":{
         "encoding":"string",
         "data":"value23"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key24"
      },
      "value":{
         "encoding":"string",
         "data":"value24"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key25"
      },
      "value":{
         "encoding":"string",
         "data":"value25"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key26"
      },
      "value":{
         "encoding":"string",
         "data":"value26"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key27"
      },
      "value":{
         "encoding":"string",
         "data":"value27"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key28"
      },
      "value":{
         "encoding":"string",
         "data":"value28"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key29"
      },
      "value":{
         "encoding":"string",
         "data":"value29"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key30"
      },
      "value":{
         "encoding":"string",
         "data":"value30"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key31"
      },
      "value":{
         "encoding":"string",
         "data":"value31"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key32"
      },
      "value":{
         "encoding":"string",
         "data":"value32"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key33"
      },
      "value":{
         "encoding":"string",
         "data":"value33"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key34"
      },
      "value":{
         "encoding":"string",
         "data":"value34"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key35"
      },
      "value":{
         "encoding":"string",
         "data":"value35"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key36"
      },
      "value":{
         "encoding":"string",
         "data":"value36"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key37"
      },
      "value":{
         "encoding":"string",
         "data":"value37"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key38"
      },
      "value":{
         "encoding":"string",
         "data":"value38"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key39"
      },
      "value":{
         "encoding":"string",
         "data":"value39"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key40"
      },
      "value":{
         "encoding":"string",
         "data":"value40"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key41"
      },
      "value":{
         "encoding":"string",
         "data":"value41"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key42"
      },
      "value":{
         "encoding":"string",
         "data":"value42"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key43"
      },
      "value":{
         "encoding":"string",
         "data":"value43"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key44"
      },
      "value":{
         "encoding":"string",
         "data":"value44"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key45"
      },
      "value":{
         "encoding":"string",
         "data":"value45"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key46"
      },
      "value":{
         "encoding":"string",
         "data":"value46"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key47"
      },
      "value":{
         "encoding":"string",
         "data":"value47"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key48"
      },
      "value":{
         "encoding":"string",
         "data":"value48"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key49"
      },
      "value":{
         "encoding":"string",
         "data":"value49"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key50"
      },
      "value":{
         "encoding":"string",
         "data":"value50"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key51"
      },
      "value":{
         "encoding":"string",
         "data":"value51"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key52"
      },
      "value":{
         "encoding":"string",
         "data":"value52"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key53"
      },
      "value":{
         "encoding":"string",
         "data":"value53"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key54"
      },
      "value":{
         "encoding":"string",
         "data":"value54"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key55"
      },
      "value":{
         "encoding":"string",
         "data":"value55"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key56"
      },
      "value":{
         "encoding":"string",
         "data":"value56"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key57"
      },
      "value":{
         "encoding":"string",
         "data":"value57"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key58"
      },
      "value":{
         "encoding":"string",
         "data":"value58"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key59"
      },
      "value":{
         "encoding":"string",
         "data":"value59"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key60"
      },
      "value":{
         "encoding":"string",
         "data":"value60"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key61"
      },
      "value":{
         "encoding":"string",
         "data":"value61"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key62"
      },
      "value":{
         "encoding":"string",
         "data":"value62"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key63"
      },
      "value":{
         "encoding":"string",
         "data":"value63"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key64"
      },
      "value":{
         "encoding":"string",
         "data":"value64"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key65"
      },
      "value":{
         "encoding":"string",
         "data":"value65"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key66"
      },
      "value":{
         "encoding":"string",
         "data":"value66"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key67"
      },
      "value":{
         "encoding":"string",
         "data":"value67"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key68"
      },
      "value":{
         "encoding":"string",
         "data":"value68"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key69"
      },
      "value":{
         "encoding":"string",
         "data":"value69"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key70"
      },
      "value":{
         "encoding":"string",
         "data":"value70"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key71"
      },
      "value":{
         "encoding":"string",
         "data":"value71"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key72"
      },
      "value":{
         "encoding":"string",
         "data":"value72"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key73"
      },
      "value":{
         "encoding":"string",
         "data":"value73"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key74"
      },
      "value":{
         "encoding":"string",
         "data":"value74"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key75"
      },
      "value":{
         "encoding":"string",
         "data":"value75"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key76"
      },
      "value":{
         "encoding":"string",
         "data":"value76"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key77"
      },
      "value":{
         "encoding":"string",
         "data":"value77"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key78"
      },
      "value":{
         "encoding":"string",
         "data":"value78"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key79"
      },
      "value":{
         "encoding":"string",
         "data":"value79"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key80"
      },
      "value":{
         "encoding":"string",
         "data":"value80"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key81"
      },
      "value":{
         "encoding":"string",
         "data":"value81"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key82"
      },
      "value":{
         "encoding":"string",
         "data":"value82"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key83"
      },
      "value":{
         "encoding":"string",
         "data":"value83"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key84"
      },
      "value":{
         "encoding":"string",
         "data":"value84"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key85"
      },
      "value":{
         "encoding":"string",
         "data":"value85"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key86"
      },
      "value":{
         "encoding":"string",
         "data":"value86"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key87"
      },
      "value":{
         "encoding":"string",
         "data":"value87"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key88"
      },
      "value":{
         "encoding":"string",
         "data":"value88"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key89"
      },
      "value":{
         "encoding":"string",
         "data":"value89"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key90"
      },
      "value":{
         "encoding":"string",
         "data":"value90"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key91"
      },
      "value":{
         "encoding":"string",
         "data":"value91"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key92"
      },
      "value":{
         "encoding":"string",
         "data":"value92"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key93"
      },
      "value":{
         "encoding":"string",
         "data":"value93"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key94"
      },
      "value":{
         "encoding":"string",
         "data":"value94"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key95"
      },
      "value":{
         "encoding":"string",
         "data":"value95"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key96"
      },
      "value":{
         "encoding":"string",
         "data":"value96"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key97"
      },
      "value":{
         "encoding":"string",
         "data":"value97"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key98"
      },
      "value":{
         "encoding":"string",
         "data":"value98"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key99"
      },
      "value":{
         "encoding":"string",
         "data":"value99"
      }
   },
   {
      "key":{
         "encoding":"string",
         "data":"key100"
      },
      "value":{
         "encoding":"string",
         "data":"value100"
      }
   }
]'  http://localhost:8080/set